#!/usr/bin/env Rscript
# visualize a development of SAT solving process
# USAGE: mk59.R runs [title]
# where runs is a filename that contains a list of CSV filenames which are generated by sat-benchmark
#
# SHORT TUTORIAL
# 1. parallel "mios-era -e {} --dumpAS=1000 > dump-{}.csv" ::: *.cnf
# 2. parallel "echo -n {}, ; tail -1 {} | sed -e 's/.*\".*\",\([^,]*\),.*/\1/g'" ::: *.csv | sort -n -k 2 -t, | gawk -F, '{ print $1 }' > dump.runs
# 3. mk59.R dump.runs

library("ggplot2")
library("grid")
version = "0.12.1"

getData = function (t, p) {
    df <- read.csv(as.character(t[[1]]), header=T, sep=",", comment="#")
    rs <- subset(df, "RESTART" == config)
    if (0 == nrow(rs)) {
        rs = data.frame(config=c("RESTART"), ci=c(1), level=c(0), d0=c(0), d1=c(0), d2=c(0)) }
    rd <- subset(df, "REDUCTION" == config)
    if (0 == nrow(rd)) {
        rd = data.frame(config=c("REDUCTION"), ci=c(1), level=c(0), d0=c(0), d1=c(0), d2=c(0)) }
    df <- subset(df, "RESTART" != config & "REDUCTION" != config)
    if (p && t[[2]] != "") {
        df[["config"]] = sub("^ +", "", as.character(t[[2]]))
        dr[["config"]] = sub("^ +", "", as.character(t[[2]]))
        ds[["config"]] = sub("^ +", "", as.character(t[[2]]))
    }  else {
        rs[["config"]] = sub("^ +", "", as.character(df[1,1]))
        rd[["config"]] = sub("^ +", "", as.character(df[1,1]))
    }
    df1 <- data.frame(id=df[["config"]], num=df[["ci"]], value=df[["d0"]], type="restart")
    df2 <- data.frame(id=df[["config"]], num=df[["ci"]], value=df[["d1"]], type="reduction")
    df3 <- data.frame(id=df[["config"]], num=df[["ci"]], value=df[["d2"]], type="target")
    df4 <- data.frame(id=rs[["config"]], num=rs[["ci"]], value=rs[["d0"]], type="res_point")
    df5 <- data.frame(id=rd[["config"]], num=rd[["ci"]], value=rd[["d1"]], type="red_point")
    df6 <- data.frame(id=rs[["config"]], num=rs[["ci"]], value=rs[["d2"]], type="res_sum")
    df7 <- data.frame(id=rd[["config"]], num=rd[["ci"]], value=rd[["d2"]], type="red_sum")
    rbind(df1, df2, df3, df4, df5, df6, df7)
}

graph = function (df, kind, mes, logGraph=FALSE) {
    d <- subset(df, grepl(kind, df$type))
    g <- ggplot(NULL) # data=d, aes(x=num, y=value, color=id))
    g <- g + geom_line(data=d, aes(x=num, y=value, color=id), size=0.4)
    g <- g + theme(legend.title=element_blank(),
                   legend.position="top",
                   legend.justification=c(0,0),
                   legend.direction="horizontal",
                   plot.margin=grid::unit(c(8,8,8,8), "pt"))
    if (logGraph == TRUE) {
        g <- g + scale_x_log10(limits=c(min(df$num),max(df$num)))
    } else {
        g <- g + scale_x_continuous(limits=c(min(df$num),max(df$num)))
    }
    g <- g + scale_y_continuous(limits=c(min(d$value),max(d$value)))
    g <- g + labs(subtitle=mes, x="conflict index", y=NULL)
    g
}

(function() {
    df <- list()
    args <- commandArgs(trailingOnly=TRUE)
    ts <-format(as.POSIXlt(Sys.time()), "%Y-%m-%dT%H:%M:%S")
    exps <- args[1]
    runs <- read.csv(exps, comment="#", sep=",", header=F)
    name <- gsub("\\.[^.]+$", "", exps)
    targetPDF <- paste("sim-", name, ".pdf", sep="")
    for (i in seq(nrow(runs))) { df = rbind(df, getData(runs[i,], 1 < ncol(runs))); }
    cairo_pdf(filename=targetPDF, width=9, height=12, antialias="subpixel", onefile=TRUE)

    dt <- subset(df, "target" == df$type)
    g1 <- graph(df,"target",   " - Ideal Similarity, restart/reduction at cross/triangle points", FALSE)
    rs <- subset(df, "res_point" == df$type)
    if (1 < nrow(rs)) {
        rs[["value"]] <- 0.7 * min(dt$value) + 0.3 * max(dt$value)
        g1 <- g1 + geom_point(data=rs, aes(num,value,color=id), size=0.7, shape=3)
    }
    rd <- subset(df, "red_point" == df$type)
    if (1 < nrow(rd)) {
        rd[["value"]] <- 0.8 * min(dt$value) + 0.2 * max(dt$value)
        g1 <- g1 + geom_point(data=rd, aes(num,value,color=id), size=0.2, shape=2)
    }
    desc = if (1 < length(args)) args[2] else name
    g1 <- g1 + labs(title=paste("Cosine similarity on assignment", "(", desc, ")"))
    g1 <- g1 + annotate("text",
                        x=0.2*min(dt$num) + 0.8*max(dt$num),
                        y=0.9*min(dt$value) + 0.1*max(dt$value),
                        label=paste(format(as.POSIXlt(Sys.time()), "%Y-%m-%dT%H:%M:%S"), " ", "drawn with mk59.R (ver. ", version, ")", sep=""),
#                        color="bisque4", size=2.6)
                        color="gray50", size=2.6)

    df[["id"]] = gsub("=.+", "", df[["id"]])
    g2 <- graph(df, "restart",   " - Restart-based similarity", TRUE)
    g3 <- graph(df, "reduction", " - Reduction-based similarity", TRUE)
    g4 <- graph(df, "res_sum",  " - Restart-based similarity sum", TRUE)
    g5 <- graph(df, "red_sum",  " - Reduction-based similarity sum", TRUE)

    grid.newpage()
    pushViewport(viewport(layout=grid.layout(3,2)))
    print(g1, vp=viewport(layout.pos.row=1, layout.pos.col=c(1,2)))
    print(g2, vp=viewport(layout.pos.row=2, layout.pos.col=1))
    print(g3, vp=viewport(layout.pos.row=2, layout.pos.col=2))
    print(g4, vp=viewport(layout.pos.row=3, layout.pos.col=1))
    print(g5, vp=viewport(layout.pos.row=3, layout.pos.col=2))
    ggsave(filename=targetPDF, width=9, height=12, scale=1.0, dpi=400)
})()
