#!/usr/bin/env Rscript
# visualize a development of SAT solving process
# USAGE: mkTrans.R runs [title]
# where runs is a filename that contains a list of CSV filenames which are generated by sat-benchmark, or a csv file

library("ggplot2")
library("grid")
version = "0.1.1"

getData = function (t, p) {
    df <- read.csv(as.character(t[[1]]), header=T, sep=",", comment="#")
    if (p && t[[2]] != "") {
        tag = sub("^ +", "", as.character(t[[2]]))
    }  else {
        tag = sub("^ +", "", as.character(t[[1]]))
    }
    df1 <- data.frame(id=paste("#total", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["NumOfRestart"]],
                      type="target")
    df2 <- data.frame(id=paste("#blocked", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["NumOfBlockRestart"]],
                      type="target")
    df3 <- data.frame(id=paste("#geometric", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["NumOfGeometricRestart"]],
                      type="target")
    df4 <- data.frame(id=paste("FAST", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaDFast"]],
                      type="distances")
    df5 <- data.frame(id=paste("SLOW", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaDSlow"]],
                      type="distances")
    df6 <- data.frame(id=tag, # paste("distance ratio", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaDFast"]]/df[["emaDSlow"]],
                      type="distance ratio")
    df7 <- data.frame(id=paste("FAST", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaAFast"]],
                      type="assigns")
    df8 <- data.frame(id=paste("SLOW", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaASlow"]],
                      type="assigns")
    df9 <- data.frame(id=tag, # paste("assign ratio", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaAFast"]]/df[["emaASlow"]],
                      type="assign ratio")
    rbind(df1, df2, df3, df4, df5, df6, df7, df8, df9)
}

graph = function (df, kind, mes, logGraph=FALSE) {
    d <- subset(df, grepl(kind, df$type))
    g <- ggplot(NULL)
    g <- g + geom_line(data=d, aes(x=num, y=value, color=id), size=0.4)
    g <- g + theme(legend.title=element_blank(),
                   legend.position="top",
                   legend.justification=c(0,0),
                   legend.direction="horizontal",
                   plot.margin=grid::unit(c(8,8,8,8), "pt"))
    if (logGraph == TRUE) {
        g <- g + scale_x_log10(limits=c(min(df$num),max(df$num)))
    } else {
        g <- g + scale_x_continuous(limits=c(min(df$num),max(df$num)))
    }
    g <- g + scale_y_continuous(limits=c(min(d$value),max(d$value)))
    g <- g + labs(subtitle=mes, x="conflict index", y=NULL)
    g
}

(function() {
    df <- list()
    args <- commandArgs(trailingOnly=TRUE)
    filename <- args[1]
    if (grep("\\.csv$", args[1])) {
        name <- gsub("\\.[^.]+$", "", filename)
        df <- getData(args[1], FALSE)
        targetPDF <- paste("sim-", name, ".pdf", sep="")
    } else {
        exps <- args[1]
        runs <- read.csv(exps, comment="#", sep=",", header=F)
        name <- gsub("\\.[^.]+$", "", exps)
        targetPDF <- paste("sim-", name, ".pdf", sep="")
        for (i in seq(nrow(runs))) { df = rbind(df, getData(runs[i,], 1 < ncol(runs))); }
    }
    cairo_pdf(filename=targetPDF, width=9, height=12, antialias="subpixel", onefile=TRUE)
    g1 <- graph(df, "target",   "Restart", FALSE)
    desc = if (1 < length(args)) args[2] else filename
    g1 <- g1 + labs(title=paste("State Evolution against Conflict Index", "(", desc, ")"))
    dt <- subset(df, grepl("target", df$type))
    g1 <- g1 + annotate("text",
                        x=0.2*min(df$num) + 0.8*max(df$num),
                        y=0.9*min(dt$value) + 0.1*max(dt$value),
                        label=paste(format(as.POSIXlt(Sys.time()), "%Y-%m-%dT%H:%M:%S"), " ",
                                    "drawn with mkTrans.R (ver. ", version, ")", sep=""),
                        color="gray50", size=2.6)

    df[["id"]] = gsub("=.+", "", df[["id"]])
    g2 <- graph(df, "distances", "FORCING RESTART - based on LBD", TRUE)
    g3 <- graph(df, "distance ratio",  " - LBD evolution ratio", TRUE)
    g4 <- graph(df, "assigns",   "BLOCKING RESTART - based on assignment", TRUE)
    g5 <- graph(df, "assign ratio",    " - Assignment evolution ratio", TRUE)

    grid.newpage()
    pushViewport(viewport(layout=grid.layout(3,2)))
    print(g1, vp=viewport(layout.pos.row=1, layout.pos.col=c(1,2)))
    print(g2, vp=viewport(layout.pos.row=2, layout.pos.col=1))
    print(g3, vp=viewport(layout.pos.row=3, layout.pos.col=1))
    print(g4, vp=viewport(layout.pos.row=2, layout.pos.col=2))
    print(g5, vp=viewport(layout.pos.row=3, layout.pos.col=2))
    ggsave(filename=targetPDF, width=9, height=12, scale=1.0, dpi=400)
})()
