#!/usr/bin/env Rscript
# count the number of SAT problems and the number of UNSAT problems
# USAGE: count-SU run [threshold]
# where run is a filename that contains a list of CSV filenames which are generated by sat-benchmark

getData = function (t, k) {
    df <- read.csv(as.character(t[[1]]), header=T, sep=",", comment="#")
    if (0 < k) {
        df1 <- df[df$time <= k,]
    }
    if (ncol(df1) == 5) {
        nsat <- nrow(df1[df1$valid==1,])
        nuns <- nrow(df1[df1$valid==0,])
        cat(paste(t[[1]], ", SAT=", nsat, ", UNSAT=", nuns, ", solved=", nrow(df1), ", problems=", nrow(df), "\n", sep=""))
    } else {
        cat(paste(t[[1]], " has no data.\n", sep=""))
    }
}

(function() {
    args <- commandArgs(trailingOnly=TRUE)
    fname <- args[1]
    cut <- -1
    if (1 < length(args)) {
        cut <- as.integer(args[2])
    }
    if (grepl("\\.csv$", fname)) {
        getData(fname, cut)
    } else {
        runs <- read.csv(fname, comment="#", sep=",", header=F)
        for (i in seq(nrow(runs))) { getData(runs[i,], cut); }
    }
})()
