#!/usr/bin/env Rscript
# generate a cactus plot (png and pdf) from CVS files
# USAGE: mios-count runs
# where runs is a filename that contains a list of CSV filenames which are generated by sat-benchmark

getData = function (t) {
    df1 <- read.csv(as.character(t[[1]]), header=T, sep=",", comment="#")
    if (ncol(df1) == 5) {
        nsat <- nrow(df1[df1$valid==1,])
        nuns <- nrow(df1[df1$valid==0,])
        cat(paste(t[[1]], ",SAT=", nsat, ",UNSAT=", nuns, "\n", sep=""))
    } else {
        cat(paste(t[[1]], " has no data.\n", sep=""))
    }
}

(function() {
    arg <- commandArgs(trailingOnly=TRUE)[1]
    if (grepl("\\.csv$", arg)) {
        getData(arg)
    } else {
        runs <- read.csv(arg, comment="#", sep=",", header=F)
        for (i in seq(nrow(runs))) { getData(runs[i,]); }
    }
})()
