#!/usr/bin/env Rscript
# generate a cactus plot (png and pdf) from CVS files
# USAGE: mkCactus.R runs
# where runs is a filename that contains a list of CSV filenames which are generated by sat-benchmark
library("ggplot2")

getData <- function (t, p) {
	df1 = read.csv(as.character(t[[1]]), header=T, sep=",", comment="#")
	df2 = df1[order(df1[,4]),]         	# sort by time (the 4th column)
	if (p && t[[2]] != "") { df2[1] = sub("^ +", "", as.character(t[[2]])) }
	df2[[2]] = 1:nrow(df2)            	# reassign rownumbers
	df2
	}

graph <- function (d = merged) {
      g <- ggplot(merged, aes(num, time, color=solver))
      g <- g + geom_point(size=0.5)
      g <- g + geom_line(data=merged,size=0.6)
      g <- g + theme(legend.position = c(0.88,0.1), legend.justification = c(1,0))
      g <- g + scale_x_continuous(limits=c(0,355),breaks=seq(0,355,10))
      g <- g + scale_y_continuous(limits=c(0,410) ,breaks=seq(0,410,100))
      g <- g + xlab("#solved") + ylab("execution time [sec]") + ggtitle("Cactus plot on SAT-Race 2017 Main track (short timeout)")
      print(g)
}

merged = list()

args <- commandArgs(trailingOnly=TRUE)
if (0 < length(args)){
    exps <- args[1]
    name <- gsub("\\.[^.]+$", "", exps)
    targetPDF <- paste("cactus-", name, ".pdf", sep="")
    targetPNG <- paste("cactus-", name, ".png", sep="")
  } else {
     exps <- "runs"
     name <- "runs"
     targetPDF <- "cactus-SC17main.pdf"
     targetPNG <- "cactus-SC17main.png"
  }
runs <- read.csv(exps, comment="#", sep=",", header=F)
withTag <- 1 < ncol(runs)
for (i in seq(nrow(runs))) { merged = rbind(merged, getData(runs[i,], withTag)); }

pdf(targetPDF, width=10, height=7)
graph(merged)
ggsave(targetPDF)
ggsave(file=targetPNG, width=9, height=6, dpi=200)
dev.off()
