#!/usr/bin/env Rscript
# visualize a development of SAT solving process
# USAGE: mkEvo.R runs [title]
# where runs is a filename that contains a list of CSV filenames which are generated by sat-benchmark, or a csv file

library("ggplot2")
library("grid")
version = "0.5.0"

getData = function (single, t, p) {
    df <- read.csv(as.character(t[[1]]), header=T, sep=",", comment="#")
    if (single) {
        tag = ""
    } else if (p && t[[2]] != "") {
        tag = sub("^ +", "", as.character(t[[2]]))
    }  else {
        tag = sub("^ +", "", as.character(t[[1]]))
    }
    df1 <- data.frame(id=paste("#restart", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["NumOfRestart"]],
                      type="target")
    df2 <- data.frame(id=paste("#blocked", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["NumOfBlockRestart"]],
                      type="target")
    df3 <- data.frame(id=paste("#geometric", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["NumOfGeometricRestart"]],
                      type="target")
    df4 <- data.frame(id=paste("FAST", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaDFast"]],
                      type="distances")
    df5 <- data.frame(id=paste("SLOW", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaDSlow"]],
                      type="distances")
    df6 <- data.frame(id=paste("distance ratio ", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaDFast"]]/df[["emaDSlow"]],
                      type="distance ratio")
    df7 <- data.frame(id=paste("FAST", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaAFast"]],
                      type="assigns")
    df8 <- data.frame(id=paste("SLOW", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaASlow"]],
                      type="assigns")
    df9 <- data.frame(id=paste("assign ratio", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaAFast"]]/df[["emaASlow"]],
                      type="assign ratio")
    dfa <- data.frame(id=paste("FAST", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaLFast"]],
                      type="backjump level")
    dfb <- data.frame(id=paste("SLOW", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaLSlow"]],
                      type="backjump level")
    dfc <- data.frame(id=paste("level ratio", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaLFast"]]/df[["emaLSlow"]],
                      type="blevel ratio")
    dfd <- data.frame(id=paste("FAST", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaRFast"]],
                      type="conflict level")
    dfe <- data.frame(id=paste("SLOW", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaRSlow"]],
                      type="conflict level")
    dff <- data.frame(id=paste("level ratio", tag),
                      num=df[["NumOfBackjump"]],
                      value=df[["emaRFast"]]/df[["emaRSlow"]],
                      type="clevel ratio")
    rbind(df1, df2, df3, df4, df5, df6, df7, df8, df9, dfa, dfb, dfc, dfd, dfe, dff)
}

graph = function (df, kind, mes, logGraph=FALSE) {
    d <- subset(df, grepl(kind, df$type))
    g <- ggplot(NULL)
    g <- g + geom_line(data=d, aes(x=num, y=value, color=id), size=0.4)
    g <- g + theme(plot.margin=grid::unit(c(8,8,8,8), "pt"))
    g <- g + scale_y_continuous(limits=c(min(d$value),max(d$value)))
    if (logGraph == TRUE) {
        g <- g + theme(legend.position="none")
        g <- g + scale_x_log10(limits=c(min(df$num),max(df$num)))
        g <- g + labs(subtitle=mes, x=NULL, y=NULL)
    } else {
        g <- g + theme(legend.title=element_blank(),
                       legend.position="top",
                       legend.justification=c(0,0),
                       legend.direction="horizontal")
        g <- g + scale_x_continuous(limits=c(min(df$num),max(df$num)))
        g <- g + labs(subtitle=mes, x="conflict index", y=NULL)
    }
    g
}

(function() {
    df <- list()
    args <- commandArgs(trailingOnly=TRUE)
    filename <- args[1]
    if (grep("\\.csv$", args[1])) {
        name <- gsub("\\.[^.]+$", "", filename)
        df <- getData(TRUE, filename, FALSE)
        if (dirname(name) != "") {
            targetPDF <- paste(dirname(name), "/ema-", basename(name), ".pdf", sep="")
        } else {
            targetPDF <- paste("ema-", name, ".pdf", sep="")
        }
    } else {
        exps <- args[1]
        runs <- read.csv(exps, comment="#", sep=",", header=F)
        name <- gsub("\\.[^.]+$", "", exps)
        if (dirname(name) != "") {
            targetPDF <- paste(dirname(name), "/sim-", basename(name), ".pdf", sep="")
        } else {
            targetPDF <- paste("sim-", name, ".pdf", sep="")
        }
        for (i in seq(nrow(runs))) { df = rbind(df, getData(FALSE, runs[i,], 1 < ncol(runs))); }
    }
    cairo_pdf(filename=targetPDF, width=9, height=12, antialias="subpixel", onefile=TRUE)
    g1 <- graph(df, "target",   "Restart", FALSE)
    desc = if (1 < length(args)) args[2] else filename
    g1 <- g1 + labs(title=paste("State Evolution against Conflict Index", "(", desc, ")"))
    dt <- subset(df, grepl("target", df$type))
    g1 <- g1 + annotate("text",
                        x=0.2*min(df$num) + 0.8*max(df$num),
                        y=0.9*min(dt$value) + 0.1*max(dt$value),
                        label=paste(format(as.POSIXlt(Sys.time()), "%Y-%m-%dT%H:%M:%S"), " ",
                                    "drawn with mkTrans.R (ver. ", version, ")", sep=""),
                        color="gray50", size=2.6)

    df[["id"]] = gsub("=.+", "", df[["id"]])
    g2 <- graph(df, "target",         " - Log scaled restart", TRUE)
    g3 <- graph(df, "assigns",        "EMA of the number of assignment ->  blocking restart", TRUE)
    g4 <- graph(df, "assign ratio",   "", TRUE)
    g5 <- graph(df, "distances",      "EMA of Literal Block Distance -> forcing restart", TRUE)
    g6 <- graph(df, "distance ratio", "", TRUE)
    g7 <- graph(df, "conflict level", "EMA of Decision Level at conflict", TRUE)
    g8 <- graph(df, "clevel ratio",   "", TRUE)
    g9 <- graph(df, "backjump level", "EMA of Decision Level by BackJump", TRUE)
    ga <- graph(df, "blevel ratio",   "", TRUE)
    grid.newpage()
    pushViewport(viewport(layout=grid.layout(6,2),width=0.94,height=0.94))
    print(g1, vp=viewport(layout.pos.row=1, layout.pos.col=c(1,2)))
    print(g2, vp=viewport(layout.pos.row=2, layout.pos.col=c(1,2)))
    print(g3, vp=viewport(layout.pos.row=3, layout.pos.col=1))
    print(g4, vp=viewport(layout.pos.row=3, layout.pos.col=2))
    print(g5, vp=viewport(layout.pos.row=4, layout.pos.col=1))
    print(g6, vp=viewport(layout.pos.row=4, layout.pos.col=2))
    print(g7, vp=viewport(layout.pos.row=5, layout.pos.col=1))
    print(g8, vp=viewport(layout.pos.row=5, layout.pos.col=2))
    print(g9, vp=viewport(layout.pos.row=6, layout.pos.col=1))
    print(ga, vp=viewport(layout.pos.row=6, layout.pos.col=2))
    ggsave(filename=targetPDF, width=9, height=12, scale=1.0, dpi=400)
})()
